services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: duke_capstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - duke_capstone_db:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TEAMMATE_PREFS_KEY: ${TEAMMATE_PREFS_KEY}
      AWS_REGION: ${AWS_REGION}
      OTP_SES_SOURCE_EMAIL: ${OTP_SES_SOURCE_EMAIL}
      OTP_EMAIL_SUBJECT: ${OTP_EMAIL_SUBJECT}
      OTP_FORWARD_TO_EMAIL: ${OTP_FORWARD_TO_EMAIL}
      OTP_STATIC_CODE: ${OTP_STATIC_CODE}
      CORS_ORIGINS: http://localhost:5173
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  duke_capstone_db:
